### ISSUE TITLE
Pass Acid3

### ISSUE THREAD

**Issue by arhadthedev** [arhadthedev/febreng#13]
URL of the test: http://acid3.acidtests.org/

What is exactly tested: https://www.webstandards.org/action/acid3/guide/

Why don't modern Chrome and Firefox pass the Acid3 test anymore: https://news.ycombinator.com/item?id=15256890

A list of tests as described in source code of `http://acid3.acidtests.org/` (see lines `// test ...: ...`)
- [ ] test 0: whether removing an element that is the last child correctly recomputes styles for the new last child
- [ ] test 1: NodeFilters and Exceptions
- [ ] test 2: Removing nodes during iteration
- [ ] test 3: the infinite iterator
- [ ] test 4: ignoring whitespace text nodes with node iterators
- [ ] test 5: ignoring whitespace text nodes with tree walkers
- [ ] test 6: walking outside a tree
- [ ] test 7: basic ranges tests
- [ ] test 8: moving boundary points
- [ ] test 9: extractContents() in a Document
- [ ] test 10: Ranges and Attribute Nodes
- [ ] test 11: Ranges and Comments
- [ ] test 12: Ranges under mutations: insertion into text nodes
- [ ] test 13: Ranges under mutations: deletion
- [ ] test 14: HTTP - Content-Type: image/png
- [ ] test 15: HTTP - Content-Type: text/plain
- [ ] test 16: <object> handling and HTTP status codes
- [ ] test 17: hasAttribute
- [ ] test 18: nodeType (this test also relies on accurate parsing of the document)
- [ ] test 19: value of constants
- [ ] test 20: nulls bytes in various places
- [ ] test 21: basic namespace stuff
- [ ] test 22: createElement() with invalid tag names
- [ ] test 23: createElementNS() with invalid tag names
- [ ] test 24: event handler attributes
- [ ] test 25: test namespace checking in createDocumentType, and
- [ ] test 26: check that document tree survives while still accessible
- [ ] test 27: a continuation of the previous test
- [ ] test 28: getElementById()
- [ ] test 29: check that whitespace survives cloning
- [ ] test 30: dispatchEvent()
- [ ] test 31: event.stopPropagation() and capture
- [ ] test 32: events bubbling through Document node
- [ ] test 33: basic tests for selectors - classes, attributes
- [ ] test 34: :lang() and [|=]
- [ ] test 35: :first-child
- [ ] test 36: :last-child
- [ ] test 37: :only-child
- [ ] test 38: :empty
- [ ] test 39: :nth-child, :nth-last-child
- [ ] test 40: :first-of-type, :last-of-type, :only-of-type, :nth-of-type, :nth-last-of-type
- [ ] test 41: :root, :not()
- [ ] test 42: +, ~, >, and ' ' in dynamic situations
- [ ] test 43: :enabled, :disabled, :checked, etc
- [ ] test 44: selectors without spaces before a "*"
- [ ] test 45: cssFloat and the style attribute
- [ ] test 46: media queries
- [ ] test 47: 'cursor' and CSS3 values
- [ ] test 48: :link and :visited
- [ ] test 49: basic table accessor ping test create*, delete*, and *
- [ ] test 50: construct a table, and see if the table is as expected
- [ ] test 51: test the ordering and creation of rows
- [ ] test 52: <form> and .elements
- [ ] test 53: changing an <input> dynamically
- [ ] test 54: changing a parsed <input>
- [ ] test 55: moved checkboxes should keep their state
- [ ] test 56: cloned radio buttons should keep their state
- [ ] test 57: HTMLSelectElement.add()
- [ ] test 58: HTMLOptionElement.defaultSelected
- [ ] test 59: attributes of <button> elements
- [ ] test 60: className vs "class" vs attribute nodes
- [ ] test 61: className and the class attribute: space preservation
- [ ] test 62: check that DOM attributes and content attributes aren't equivalent
- [ ] test 63: attributes of the <area> element
- [ ] test 64: more attribute tests
- [ ] test 65: bring in a couple of SVG files and some HTML files dynamically - preparation for later tests in this bucket
- [ ] test 66: localName on text nodes (and now other things), from Sylvain Pasche
- [ ] test 68: UTF-16 surrogate pairs, from David Chan
- [ ] test 69: check that the support files loaded -- preparation for the rest of the tests in this bucket
- [ ] test 70: XML encoding test
- [ ] test 71: HTML parsing, from Simon Pieters and Anne van Kesteren
- [ ] test 72: dynamic modification of <style> blocks' text nodes, from Jonas Sicking and Garret Smith
- [ ] test 73: nested events, from Jonas Sicking
- [ ] test 74: check getSVGDocument(), from Erik Dahlstrom
- [ ] test 80: remove the iframes and the object
- [ ] test 81: length of arrays with elisions at end
- [ ] test 82: length of arrays with elisions in the middle
- [ ] test 83: array methods
- [ ] test 84: converting numbers to strings
- [ ] test 85: strings and string-related operations
- [ ] test 86: Date tests -- methods passed no arguments
- [ ] test 87: Date tests -- years
- [ ] test 88: ES3 section 7.6:3 (unicode escapes can't be used to put non-identifier characters into identifiers)
- [ ] test 89: Regular Expressions
- [ ] test 90: Regular Expressions
- [ ] test 91: check that properties are enumerable by default
- [ ] test 92: internal properties of Function objects
- [ ] test 93: FunctionExpression semantics
- [ ] test 94: exception scope
- [ ] test 95: types of expressions
- [ ] test 96: encodeURI() and encodeURIComponent() and null bytes
- [ ] test 97: data: URI parsing
- [ ] test 98: XHTML and the DOM
- [ ] test 99: check for the weirdest bug ever
